# Generated by Django 5.2.1 on 2025-05-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bestsell',
            field=models.BooleanField(default=False),
        ),
    ]
