# Generated by Django 5.1.3 on 2025-05-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_checkoutitem_checkout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycart',
            name='added_on',
        ),
        migrations.AlterField(
            model_name='mycart',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
