# Generated by Django 5.1.3 on 2025-05-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_mycart_added_on_alter_mycart_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
