# Generated by Django 5.1.3 on 2025-05-25 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_mycart_full_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycart',
            name='area_street',
        ),
        migrations.RemoveField(
            model_name='mycart',
            name='city',
        ),
        migrations.RemoveField(
            model_name='mycart',
            name='district',
        ),
        migrations.RemoveField(
            model_name='mycart',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mycart',
            name='flat_building',
        ),
        migrations.RemoveField(
            model_name='mycart',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='mycart',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='mycart',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='mycart',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='mycart',
            name='state',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('flat_building', models.CharField(max_length=255)),
                ('area_street', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=50)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
